version: '3.9'
name: 'song-recommendation-app'
services:
  neo4j:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: $NEO4J_USER/$NEO4J_PASSWORD
    volumes:
      - ./volumes/neo4j/data:/data

  redis:
    image: redis:latest
    environment:
      REDIS_PASSWORD: $REDIS_PASSWORD
    ports:
      - 6379:6379
    volumes:
      - ./volumes/redis/data:/data

  nextjs:
    depends_on:
      - redis
      - neo4j
    build:
      dockerfile: ./Dockerfile
      args:
        RUNNER_ENV: ${RUNNER_ENV}
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
